{% set name = "scimap" %}
{% set version = "0.17.7" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 319eba50ca29045ba2fc8e2289b3af15b123abd2826f60a821c85d0b5a13aba1

build:
  number: 0

requirements:
  host:
    - numpy >=1.18.5,<2.0.0
    - pip
    - python >=3.7,<3.8
    - scanpy >=1.6.0,<2.0.0
    - poetry
  run:
    - anndata >=0.7.4,<0.8.0
    - dask[array] >=2.30.0,<3.0.0
    - gensim >=3.8.3,<4.0.0
    - llvmlite <=0.34.0
    - matplotlib >=3.2.1,<4.0.0
    - mkdocs >=1.1.2,<2.0.0
    - mkdocs-material >=7.1.1,<8.0.0
    - napari >=0.4.2,<0.5.0
    - numba <=0.51.2
    - numpy >=1.18.5,<2.0.0
    - pandas >=1.0.4,<2.0.0
    - plotly >=4.12.0,<5.0.0
    - pytest >=5.4.3,<6.0.0
    - pytest-xvfb >=2.0.0,<3.0.0
    - python >=3.7,<3.8
    - scanpy >=1.6.0,<2.0.0
    - scipy >=1.4.1,<2.0.0
    - seaborn >=0.11.0,<0.12.0
    - shapely >=1.7.1,<2.0.0
    - tifffile >=2020.11.18,<2021.0.0
    - tifffile >=2020.6.3,<2021.0.0
    - zarr >=2.5.0,<3.0.0

test:
  imports:
    - scimap

about:
  home: "https://pypi.org/project/scimap"
  license: MIT
  summary: "Spatial Single-Cell Analysis Toolkit"

