{% set name = "vitessce" %}
{% set version = "0.1.0a11" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
    - url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
      sha256: c9ec4e377de72e9d26f6fed4ffa995f2b93b3a799b00c49c427b3165243c4b31
    - url: "https://downloads.openmicroscopy.org/bio-formats/6.6.1/artifacts/bftools.zip"
      folder: bftools

build:
  number: 0

requirements:
  host:
    - pip
    - python ==3.8

  build:
    - python ==3.8
    - pip

  run:
    - aiofiles>=0.6.0
    - hypercorn>=0.11.0
    - ujson>=4.0.1
    - python==3.8
    - numpy>=1.14.0
    - pandas>=1.1.2
    - anndata>=0.7.4
    - zarr>=2.5.0
    - numcodecs>=0.7.2
    - nbsphinx>=0.7.1
    - pytest>=6.2.4
    - pandoc>=2.11.3
    - nbclean>=0.3.2
    - pip
    - loompy>=3.0.6
    - openjdk
    - scipy>=1.2.1
    - tifffile
    - ipywidgets

test:
  imports:
    - vitessce
    - tests

about:
  home: "https://github.com/vitessce/vitessce-python"
  summary: "Jupyter widget facilitating interactive visualization of spatial single-cell data with Vitessce"
