{% set name = "squidpy" %}
{% set version = "1.1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

build:
  number: 0

requirements:
  host:
    - numpy >=1.18.5, <1.20.0
    - pip
    - python >=3.7,<3.8

  run:
    - numpy >=1.18.5, <1.20.0
    - pip
    - python >=3.7,<3.8
    - anndata>=0.7.4
    - dask-image>=0.5.0
    - dask[array]>=2021.02.0
    - docrep>=0.3.1
    - leidenalg>=0.8.2
    - pandas>=1.2.0
    - scanpy>=1.8.0
    - scikit-image>=0.17.1
    - statsmodels>=0.12.0
    - tqdm>=4.50.2
    - typing_extensions
    - xarray>=0.16.1
    - zarr>=2.6.1

test:
  imports:
    - squidpy

about:
  home: "https://pypi.org/project/squidpy"
  license:  BSD-3-Clause License
  summary: "Squidpy - Spatial Single Cell Analysis in Python"
